"""WidowX real-robot low-level environment with FastAPI bridge endpoints.

The bridge runs on a single HTTP port (default 9000) and exposes:
- `POST /observation`: client pushes latest observation
- `GET  /observation`: inspect latest observation
- `GET  /act`: client fetches latest action generated by CaP-X
- `POST /act`: optional combined call (push observation + fetch action)
- `GET  /health`: health check

Direct-control mode is the default (`use_policy_server=False`):
CaP-X APIs generate joint targets and publish them to `latest_action`.
"""

from __future__ import annotations

import threading
import time
from typing import Any

import numpy as np
import requests
import uvicorn
from fastapi import FastAPI
from pydantic import BaseModel

from capx.envs.base import BaseEnv


class _ObservationPayload(BaseModel):
    observation: dict[str, Any]


class _ActPayload(BaseModel):
    observation: dict[str, Any] | None = None


class _BridgeState:
    def __init__(self) -> None:
        self.latest_observation: dict[str, Any] = {}
        self.latest_action: dict[str, Any] = {}
        self.lock = threading.Lock()


def _decode_bytes_keys(obj: Any) -> Any:
    if isinstance(obj, dict):
        out: dict[str, Any] = {}
        for k, v in obj.items():
            key = k.decode("utf-8", errors="replace") if isinstance(k, bytes) else str(k)
            out[key] = _decode_bytes_keys(v)
        return out
    if isinstance(obj, list):
        return [_decode_bytes_keys(v) for v in obj]
    return obj


def _to_jsonable(obj: Any) -> Any:
    if isinstance(obj, dict):
        return {str(k): _to_jsonable(v) for k, v in obj.items()}
    if isinstance(obj, (list, tuple)):
        return [_to_jsonable(v) for v in obj]
    if isinstance(obj, np.ndarray):
        return obj.tolist()
    if isinstance(obj, np.generic):
        return obj.item()
    if isinstance(obj, bytes):
        try:
            return obj.decode("utf-8")
        except Exception:
            return obj.hex()
    return obj


def _create_bridge_app(state: _BridgeState) -> FastAPI:
    app = FastAPI(title="widowx-bridge", version="1.0")

    @app.get("/health")
    def health() -> dict[str, str]:
        return {"status": "ok"}

    @app.post("/reset")
    def reset() -> dict[str, str]:
        with state.lock:
            state.latest_observation = {}
            state.latest_action = {}
        return {"status": "reset"}

    @app.post("/observation")
    def post_observation(payload: _ObservationPayload) -> dict[str, str]:
        with state.lock:
            state.latest_observation = _decode_bytes_keys(payload.observation)
        return {"status": "ok"}

    @app.get("/observation")
    def get_observation() -> dict[str, Any]:
        with state.lock:
            return {"observation": state.latest_observation}

    @app.get("/act")
    def get_act() -> dict[str, Any]:
        with state.lock:
            return {"action": state.latest_action}

    @app.post("/act")
    def post_act(payload: _ActPayload) -> dict[str, Any]:
        if payload.observation is not None:
            with state.lock:
                state.latest_observation = _decode_bytes_keys(payload.observation)
        with state.lock:
            return {"action": state.latest_action}

    return app


def _start_fastapi_bridge_in_background(host: str, port: int, state: _BridgeState) -> tuple[uvicorn.Server, threading.Thread]:
    app = _create_bridge_app(state)
    config = uvicorn.Config(app, host=host, port=port, log_level="warning")
    server = uvicorn.Server(config)

    thread = threading.Thread(target=server.run, daemon=True)
    thread.start()
    return server, thread


class WidowXRealLowLevel(BaseEnv):
    """Real-robot low-level env for WidowX using FastAPI server-client interaction."""

    def __init__(
        self,
        seed: int | None = None,
        privileged: bool = False,
        enable_render: bool = False,
        viser_debug: bool = False,
        msgpack_host: str = "0.0.0.0",
        msgpack_port: int = 9000,
        use_policy_server: bool = False,
        policy_url: str = "http://127.0.0.1:8000/act",
        policy_reset_url: str | None = "http://127.0.0.1:8000/reset",
        instruction: str | None = None,
        robot_name: str = "arm",
        action_dim: int = 7,
        request_timeout: float = 3.0,
        publish_raw_policy_response: bool = False,
        max_steps: int = 999999,
    ) -> None:
        del seed, privileged, enable_render, viser_debug

        super().__init__()
        self.max_steps = max_steps

        self._bridge_state = _BridgeState()
        self._bridge_server, self._bridge_thread = _start_fastapi_bridge_in_background(
            host=msgpack_host,
            port=msgpack_port,
            state=self._bridge_state,
        )

        self.use_policy_server = bool(use_policy_server)
        self.policy_url = policy_url
        self.policy_reset_url = policy_reset_url
        self.instruction = instruction
        self.robot_name = robot_name
        self.action_dim = int(action_dim)
        self.request_timeout = float(request_timeout)
        self.publish_raw_policy_response = bool(publish_raw_policy_response)

        self.obs: dict[str, Any] = {}
        self.latest_action: dict[str, Any] = {}

        self._step_count = 0
        self._sim_step_count = 0
        self._gripper_fraction = 1.0
        self._current_joints = np.zeros(7, dtype=np.float64)

    def _update_from_network(self) -> None:
        with self._bridge_state.lock:
            obs = self._bridge_state.latest_observation
        if isinstance(obs, dict) and obs:
            self.obs = obs

    def _request_policy_action(self) -> dict[str, Any] | None:
        if not self.use_policy_server or not self.policy_url:
            return None
        payload = {
            "observation": _to_jsonable(self.obs),
            "instruction": self.instruction,
        }
        try:
            resp = requests.post(self.policy_url, json=payload, timeout=self.request_timeout)
            resp.raise_for_status()
            data = resp.json()
            if isinstance(data, dict):
                return data
        except Exception:
            return None
        return None

    def _set_latest_action(self, command: dict[str, Any]) -> None:
        with self._bridge_state.lock:
            self._bridge_state.latest_action = command
        self.latest_action = command

    def _publish_policy_action(self) -> None:
        policy_data = self._request_policy_action()
        if policy_data is None:
            return

        if self.publish_raw_policy_response:
            command: dict[str, Any] = policy_data
        else:
            actions = policy_data.get("actions")
            vec: Any = actions.get(self.robot_name) if isinstance(actions, dict) else None
            if isinstance(vec, list):
                command = {
                    "timestamp": time.time(),
                    "mode": "policy",
                    self.robot_name: vec,
                    "meta": {
                        "policy_step": policy_data.get("step"),
                        "target_position": policy_data.get("target_position"),
                    },
                }
            else:
                command = policy_data

        self._set_latest_action(command)

    def reset(
        self,
        *,
        seed: int | None = None,
        options: dict[str, Any] | None = None,
    ) -> tuple[dict[str, Any], dict[str, Any]]:
        del seed, options

        if self.use_policy_server and self.policy_reset_url:
            try:
                requests.post(self.policy_reset_url, timeout=self.request_timeout)
            except Exception:
                pass

        start = time.time()
        while not self.obs:
            self._update_from_network()
            if self.obs:
                break
            if time.time() - start > 10.0:
                break
            time.sleep(0.1)

        self._step_count = 0
        self._sim_step_count = 0
        return self.obs, {}

    def step(self, action: Any) -> tuple[dict[str, Any], float, bool, bool, dict[str, Any]]:
        del action
        self._step_count += 1
        self._update_from_network()
        obs = self.get_observation()
        reward = self.compute_reward()
        terminated = self.task_completed()
        truncated = self._step_count >= self.max_steps
        return obs, reward, terminated, truncated, {}

    def _publish_joint_target_command(self, joints: np.ndarray) -> None:
        target = np.asarray(joints, dtype=np.float64).reshape(-1)
        self._current_joints = (
            target[:7] if target.size >= 7 else np.pad(target, (0, max(0, 7 - target.size)))
        )
        action_vec = np.zeros(self.action_dim, dtype=np.float64)
        fill = min(action_vec.size, target.size)
        action_vec[:fill] = target[:fill]
        if action_vec.size > fill:
            action_vec[-1] = float(self._gripper_fraction)

        command = {
            "timestamp": time.time(),
            "mode": "joint_target",
            self.robot_name: action_vec.tolist(),
        }
        self._set_latest_action(command)

    def move_to_joints_blocking(
        self,
        joints: np.ndarray,
        *,
        tolerance: float = 0.05,
        max_steps: int = 250,
    ) -> None:
        del tolerance, max_steps
        self._publish_joint_target_command(joints)
        self._sim_step_count += 1

    def _set_gripper(self, fraction: float) -> None:
        self._gripper_fraction = float(np.clip(fraction, 0.0, 1.0))

    def _step_once(self) -> None:
        self._update_from_network()
        if self.use_policy_server:
            self._publish_policy_action()
        else:
            # Direct-control mode: keep pushing current CaP-X action state to the robot loop.
            self._publish_joint_target_command(self._current_joints)
        self._sim_step_count += 1

    def get_observation(self) -> dict[str, Any]:
        self._update_from_network()
        return self.obs

    def compute_reward(self) -> float:
        return 0.0

    def task_completed(self) -> bool:
        return False
